#pragma once

#define RECACC_MEM_OFFSET_IACT 0x0000
#define RECACC_MEM_OFFSET_WGHT 0x2000
#define RECACC_MEM_OFFSET_PSUM 0x4000
#define RECACC_MEM_OFFSET_REGS 0x6000
#define RECACC_MEM_MAP_SIZE    0x8000 // covers all mapped areas

#define RECACC_MAGIC "ACC"

#define RECACC_BYTE_OFFSET(idx) (idx*4)
#define RECACC_REG_ADDR(idx)    (RECACC_MEM_OFFSET_REGS+RECACC_BYTE_OFFSET(idx))

#define RECACC_REG_IDX_CONTROL           0
#define RECACC_REG_IDX_STATUS            1
#define RECACC_REG_IDX_CHANNELS          2
#define RECACC_REG_IDX_KERNELS           3
#define RECACC_REG_IDX_IMAGE_Y           4
#define RECACC_REG_IDX_IMAGE_X           5
#define RECACC_REG_IDX_KERNEL_SIZE       6
#define RECACC_REG_IDX_CONV_C1           7
#define RECACC_REG_IDX_CONV_W1           8
#define RECACC_REG_IDX_CONV_H2           9
#define RECACC_REG_IDX_CONV_M0           10
#define RECACC_REG_IDX_CONV_M0_LAST_M1   11
#define RECACC_REG_IDX_CONV_ROW_LAST_H2  12
#define RECACC_REG_IDX_CONV_C0           13
#define RECACC_REG_IDX_CONV_C0_LAST_C1   14
#define RECACC_REG_IDX_CONV_C0W0         15
#define RECACC_REG_IDX_CONV_C0W0_LAST_C1 16
#define RECACC_REG_IDX_MAGIC             31

#define RECACC_BIT_IDX_CONTROL_RESET 0
#define RECACC_BIT_IDX_CONTROL_START 1
