#pragma once

#define RECACC_MEM_OFFSET_REGS 0x00000
#define RECACC_MEM_OFFSET_SPAD 0x80000
#define RECACC_MEM_MAP_SIZE    0x100000 // covers all mapped areas

#define RECACC_MAGIC "ACC"
#define RECACC_MIN_HW_REV 4
#define RECACC_MAX_HW_REV 4

#define RECACC_BYTE_OFFSET(idx) (idx*4)
#define RECACC_REG_ADDR(idx)    (RECACC_MEM_OFFSET_REGS+RECACC_BYTE_OFFSET(idx))

#define RECACC_REG_IDX_CONTROL           0
#define RECACC_REG_IDX_STATUS            1
#define RECACC_REG_IDX_INPUTCHS          2
#define RECACC_REG_IDX_OUTPUTCHS         3
#define RECACC_REG_IDX_IMAGE_Y           4
#define RECACC_REG_IDX_IMAGE_X           5
#define RECACC_REG_IDX_KERNEL_SIZE       6
#define RECACC_REG_IDX_CONV_C1           7
#define RECACC_REG_IDX_CONV_W1           8
#define RECACC_REG_IDX_CONV_H2           9
#define RECACC_REG_IDX_CONV_M0           10
#define RECACC_REG_IDX_CONV_M0_LAST_M1   11
#define RECACC_REG_IDX_CONV_ROWS_LAST_H2 12
#define RECACC_REG_IDX_CONV_C0           13
#define RECACC_REG_IDX_CONV_C0_LAST_C1   14
#define RECACC_REG_IDX_CONV_C0W0         15
#define RECACC_REG_IDX_CONV_C0W0_LAST_C1 16
#define RECACC_REG_IDX_BASE_ADDR_IACT    17
#define RECACC_REG_IDX_BASE_ADDR_WGHT    18
#define RECACC_REG_IDX_BASE_ADDR_PSUM    19
#define RECACC_REG_IDX_STRIDE_IACT_W     20
#define RECACC_REG_IDX_STRIDE_IACT_HW    21
#define RECACC_REG_IDX_STRIDE_WGHT_KRNL  22
#define RECACC_REG_IDX_STRIDE_WGHT_OCH   23
#define RECACC_REG_IDX_STRIDE_PSUM_OCH   24

#define RECACC_REG_IDX_ARRAY_SIZE        25
#define RECACC_REG_IDX_LINE_LENGTH_1     26
#define RECACC_REG_IDX_LINE_LENGTH_2     27
#define RECACC_REG_IDX_DATA_WIDTH        28
#define RECACC_REG_IDX_ADDR_WIDTH        29
#define RECACC_REG_IDX_CAPABILITIES      30
#define RECACC_REG_IDX_MAGIC             31
#define RECACC_REG_IDX_BIAS_REQUANT_BASE 32

#define RECACC_REG_IDX_CYCLE_COUNTER     80
#define RECACC_REG_IDX_PSUM_OVERFLOWS    81
#define RECACC_REG_IDX_CONV_STRIDE       82
// #define RECACC_REG_IDX_SPAD_STATUS       23

#define RECACC_BIT_IDX_CONTROL_RESET   0
#define RECACC_BIT_IDX_CONTROL_START   1
#define RECACC_BIT_IDX_CONTROL_REQUANT 2
#define RECACC_BIT_IDX_CONTROL_ACTMODE 3

#define RECACC_BIT_IDX_CAP_DATAFLOW     8
#define RECACC_BIT_IDX_CAP_BIAS_REQUANT 9
